<a href="https://colab.research.google.com/github/Aishwarya-1108/AMAZON/blob/main/CreditCardFraudDetection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing  the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading the dataset to pandas dataframe
credit_card_data =pd.read_csv('/content/creditcard.csv')

In [ ]:
#first five rows of the dataset
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
138718,82808,-0.479350,0.291742,1.176496,-2.387149,0.225763,-0.140455,0.213530,0.038732,1.374953,...,0.065243,0.643628,-0.471645,-0.887663,0.300513,0.130897,0.391198,0.181765,1.00,0.0
138719,82808,-8.136440,-11.620969,2.567281,3.847285,8.302748,-6.405774,-6.552874,0.728037,-0.355693,...,0.803246,-0.551467,2.380975,0.282518,0.757671,0.031566,-0.484876,0.107559,283.50,0.0
138720,82809,-0.643764,0.426174,2.199543,0.079840,-0.034291,0.720443,-0.053732,0.530447,0.299450,...,0.101108,0.364598,-0.115569,-0.340284,-0.359793,-0.570781,0.183763,0.140580,9.99,0.0
138721,82809,1.103198,-0.516509,1.043418,0.702689,-1.292794,-0.381240,-0.631045,-0.004531,-0.856200,...,-0.140908,0.002740,0.050943,0.570334,0.227712,-0.309811,0.076024,0.051107,72.00,0.0
138722,82811,-1.301314,1.216130,1.029738,1.292400,-0.062383,0.015550,0.404308,0.180961,0.073446,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset informatio
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138723 entries, 0 to 138722
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    138723 non-null  int64
 1   V1      138723 non-null  float64
 2   V2      138723 non-null  float64
 3   V3      138723 non-null  float64
 4   V4      138723 non-null  float64
 5   V5      138723 non-null  float64
 6   V6      138723 non-null  float64
 7   V7      138723 non-null  float64
 8   V8      138723 non-null  float64
 9   V9      138723 non-null  float64
 10  V10     138723 non-null  float64
 11  V11     138723 non-null  float64
 12  V12     138723 non-null  float64
 13  V13     138723 non-null  float64
 14  V14     138722 non-null  float64
 15  V15     138722 non-null  float64
 16  V16     138722 non-null  float64
 17  V17     138722 non-null  float64
 18  V18     138722 non-null  float64
 19  V19     138722 non-null  float64
 20  V20     138722 non-null  float64
 21  V21     138722 non-null  float64
 22  V22     138722 non-null  float64
 23  V23     138722 non-null  float64
 24  V24     138722 non-null  float64
 25  V25     138722 non-null  float64
 26  V26     138722 non-null  float64
 27  V27     138722 non-null  float64
 28  V28     138722 non-null  float64
 29  Amount  138722 non-null  float64
 30  Class   138722 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 32.8 MB

In [ ]:
#checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#distribution of legid transaction and fradulant transaction
credit_card_data['Class'].value_counts()

Class
0.0    138458
1.0       264
Name: count, dtype: int64

In [ ]:
#separating data for analysis
legit=credit_card_data[credit_card_data.Class==0]
fraud=credit_card_data[credit_card_data.Class==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(138458, 31)
(264, 31)

In [ ]:
#statistical measures of the data
legit.Amount.describe()

count    138458.000000
mean         91.326355
std         247.818289
min           0.000000
25%           6.040000
50%          23.990000
75%          81.000000
max       19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     264.000000
mean      115.387008
std       245.189867
min         0.000000
25%         1.000000
50%         9.560000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
#compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,51587.410854,-0.237937,0.007939,0.687613,0.131863,-0.276876,0.080863,-0.106094,0.061851,-0.086793,...,0.041947,-0.041688,-0.117943,-0.033357,0.011940,0.130242,0.023468,-0.000135,0.002096,91.326355
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

Under-Sampling

Build  a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transaction = 264

In [ ]:
legit_sample=legit.sample(n=264)

Concatenating two dataframes

In [ ]:
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
24288,33159,1.264055,-0.739260,0.988101,-0.792783,-1.206438,0.090836,-1.134445,0.172933,-0.783789,...,0.477680,1.342009,-0.106412,0.096411,0.347005,-0.041372,0.052945,0.016320,24.99,0.0
135026,81076,0.754191,-0.189615,1.591161,2.450663,-0.350678,1.921110,-0.928287,0.710143,-0.159651,...,0.426452,1.201003,0.066649,-0.613285,-0.131018,0.208942,0.103729,0.045671,88.22,0.0
61567,49893,1.156909,-0.037900,1.142505,1.073622,-0.756088,0.203264,-0.673195,0.247259,0.556348,...,0.017151,0.169969,-0.049962,-0.014016,0.399740,-0.395154,0.064945,0.023716,1.18,0.0
32015,36605,-2.996404,0.511195,-1.900544,-2.919905,1.346287,2.820428,-0.450307,1.925229,0.818944,...,-0.261918,-0.422304,0.503308,0.995549,0.579215,-0.992463,-0.003491,-0.076711,88.97,0.0
21123,31482,-0.344251,0.921223,2.002940,0.577868,0.794156,-0.006390,1.372709,-1.222325,0.072923,...,-0.327967,-0.332152,-0.228081,-0.032943,-0.687811,0.098684,-1.408370,-0.945533,2.69,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
125342,77627,-7.139060,2.773082,-6.757845,4.446456,-5.464428,-1.713401,-6.485365,3.409395,-3.053493,...,1.303250,-0.016118,-0.876670,0.382230,-1.054624,-0.614606,-0.766848,0.409424,106.90,1.0
128479,78725,-4.312479,1.886476,-2.338634,-0.475243,-1.185444,-2.112079,-2.122793,0.272565,0.290273,...,0.550541,-0.067870,-1.114692,0.269069,-0.020572,-0.963489,-0.918888,0.001454,60.00,1.0
131272,79540,-0.114361,1.036129,1.984405,3.128243,-0.740344,1.548619,-1.701284,-2.203842,-1.242265,...,-1.032935,1.196428,-0.112857,0.254719,0.696668,0.482370,0.129969,0.223924,0.20,1.0
135718,81372,-0.885254,1.790649,-0.945149,3.853433,-1.543510,0.188582,-2.988383,1.344059,-2.294535,...,0.746160,0.550802,-0.034882,-0.567608,-0.528318,0.258782,0.506893,0.176736,7.57,1.0
137705,82289,-1.464897,1.975528,-1.077145,2.819191,0.069850,-0.789044,-1.196101,0.673654,-1.363724,...,0.174099,-0.272505,-0.031549,-0.406166,0.157769,-0.104393,0.073796,-0.041570,1.00,1.0

In [ ]:
new_dataset['Class'].value_counts()

Class
0.0    264
1.0    264
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,51264.310606,-0.290679,0.078964,0.629467,0.027590,-0.360441,0.045075,-0.070487,0.134742,-0.074388,...,0.031014,-0.063333,-0.134659,-0.022894,0.014565,0.128016,0.000300,-0.040129,0.036628,86.478220
1.0,42420.212121,-5.610819,3.946507,-7.143814,4.512206,-3.977333,-1.480669,-5.936405,1.508791,-2.604923,...,0.239899,1.256981,-0.311690,-0.116543,-0.107463,0.197988,0.056528,0.489643,0.081783,115.387008

In [ ]:
#splitting the data into features into targets
X=new_dataset.drop(columns='Class',axis=1)
Y=new_dataset['Class']

print(X)
print(Y)

         Time        V1        V2        V3        V4        V5        V6  \
24288   33159  1.264055 -0.739260  0.988101 -0.792783 -1.206438  0.090836
135026  81076  0.754191 -0.189615  1.591161  2.450663 -0.350678  1.921110
61567   49893  1.156909 -0.037900  1.142505  1.073622 -0.756088  0.203264
32015   36605 -2.996404  0.511195 -1.900544 -2.919905  1.346287  2.820428
21123   31482 -0.344251  0.921223  2.002940  0.577868  0.794156 -0.006390
...       ...       ...       ...       ...       ...       ...       ...
125342  77627 -7.139060  2.773082 -6.757845  4.446456 -5.464428 -1.713401
128479  78725 -4.312479  1.886476 -2.338634 -0.475243 -1.185444 -2.112079
131272  79540 -0.114361  1.036129  1.984405  3.128243 -0.740344  1.548619
135718  81372 -0.885254  1.790649 -0.945149  3.853433 -1.543510  0.188582
137705  82289 -1.464897  1.975528 -1.077145  2.819191  0.069850 -0.789044

              V7        V8        V9  ...       V20       V21       V22  \
24288  -1.134445  0.172933 -0.783789  ...  0.148006  0.477680  1.342009
135026 -0.928287  0.710143 -0.159651  ... -0.085629  0.426452  1.201003
61567  -0.673195  0.247259  0.556348  ... -0.133775  0.017151  0.169969
32015  -0.450307  1.925229  0.818944  ... -0.727571 -0.261918 -0.422304
21123   1.372709 -1.222325  0.072923  ...  0.490413 -0.327967 -0.332152
...          ...       ...       ...  ...       ...       ...       ...
125342 -6.485365  3.409395 -3.053493  ... -0.616949  1.303250 -0.016118
128479 -2.122793  0.272565  0.290273  ... -0.718706  0.550541 -0.067870
131272 -1.701284 -2.203842 -1.242265  ...  0.732852 -1.032935  1.196428
135718 -2.988383  1.344059 -2.294535  ...  0.370041  0.746160  0.550802
137705 -1.196101  0.673654 -1.363724  ...  0.048969  0.174099 -0.272505

             V23       V24       V25       V26       V27       V28  Amount
24288  -0.106412  0.096411  0.347005 -0.041372  0.052945  0.016320   24.99
135026  0.066649 -0.613285 -0.131018  0.208942  0.103729  0.045671   88.22
61567  -0.049962 -0.014016  0.399740 -0.395154  0.064945  0.023716    1.18
32015   0.503308  0.995549  0.579215 -0.992463 -0.003491 -0.076711   88.97
21123  -0.228081 -0.032943 -0.687811  0.098684 -1.408370 -0.945533    2.69
...          ...       ...       ...       ...       ...       ...     ...
125342 -0.876670  0.382230 -1.054624 -0.614606 -0.766848  0.409424  106.90
128479 -1.114692  0.269069 -0.020572 -0.963489 -0.918888  0.001454   60.00
131272 -0.112857  0.254719  0.696668  0.482370  0.129969  0.223924    0.20
135718 -0.034882 -0.567608 -0.528318  0.258782  0.506893  0.176736    7.57
137705 -0.031549 -0.406166  0.157769 -0.104393  0.073796 -0.041570    1.00

[528 rows x 30 columns]
24288     0.0
135026    0.0
61567     0.0
32015     0.0
21123     0.0
         ...
125342    1.0
128479    1.0
131272    1.0
135718    1.0
137705    1.0
Name: Class, Length: 528, dtype: float64

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
print(X.shape,X_train.shape,X_test.shape)

(528, 30) (422, 30) (106, 30)

In [ ]:
#Modeling training
model=LogisticRegression()

In [ ]:
#training the logisticRegression model with Training data
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
#Model Evaluation
training_data_accuracy=accuracy_score(model.predict(X_train),Y_train)
print('Accuracy on Training Data:',training_data_accuracy)

Accuracy on Training Data: 0.9454976303317536

In [ ]:
testing_data_accuracy =accuracy_score(model.predict(X_test),Y_test)
print('Accuracy on Testing Data:',testing_data_accuracy)

Accuracy on Testing Data: 0.9716981132075472